meta_product_name: "Ritchie's Gardens"
meta_title: "Ritchie's Gardens - We really DIG gardens!"
meta_description: "With over 10 years experience in garden maintenance and landscaping, you are in great hands with Ritchie's Gardens."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
