meta_product_name: "Ritchie's Gardens"
meta_title: "Ritchie's Gardens - We really DIG gardens!"
meta_description: "At Ritchie's Gardens we approach garden maintenance with best-practise horticultural techniques. A local business led by an enthusiastic and passionate professional who will treat your garden as his own."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
